
server.port: 8787
logging.config: classpath:log-test.xml

online: false

spring:
  application.name: web-manager
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false
  redis:
    host: test-redis
    port: 6379
    password: redis-test-pass
    timeout: 5000
  datasource:
    url: jdbc:mysql://test-db:3306/mall?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&statementInterceptors=com.github.common.sql.ShowSqlInterceptor
    username: root
    password: root
    hikari:
      minimumIdle: 2
      maximumPoolSize: 5
      dataSourceProperties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
