
online: true
log:
  level: info
  thirdLevel: error

spring:
  application.name: task
  redis:
    host: prod-redis
    port: 6379
    password: redis-prod-pass
    timeout: 5000
  datasource:
    url: jdbc:mysql://prod-db:3306/mall?useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: root
    hikari:
      minimumIdle: 5
      maximumPoolSize: 10
      dataSourceProperties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
