
online: false
log:
  level: debug
  sqlLevel: debug
  thirdLevel: warn

spring:
  profiles.active: dev
  application.name: task
  data.redis:
    host: dev-redis
    port: 6379
    timeout: 5000
  datasource:
    url: jdbc:mysql://dev-db:3306/mall?useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&queryInterceptors=com.github.common.sql.ShowSqlInterceptor
    username: root
    password: root
    hikari:
      minimumIdle: 1
      maximumPoolSize: 1

mybatis-plus.global-config.banner: false
