
online: false
log:
  level: debug
  sqlLevel: debug
  thirdLevel: warn

spring:
  application.name: task
  redis:
    host: test-redis
    port: 6379
    password: redis-test-pass
    timeout: 5000
  datasource:
    url: jdbc:mysql://test-db:3306/mall?useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&queryInterceptors=com.github.common.sql.ShowSqlInterceptor
    username: root
    password: root
    hikari:
      minimumIdle: 2
      maximumPoolSize: 2
      dataSourceProperties:
        prepStmtCacheSize: 50
        prepStmtCacheSqlLimit: 128
        cachePrepStmts: true
        useServerPrepStmts: false

mybatis-plus.global-config.banner: false
