
server.port: 8686

online: true

log:
  level: info
  sqlLevel: info
  thirdLevel: error

spring:
  application.name: web-backend
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false
  messages.basename: i18n/message
  data.redis:
    host: prod-redis
    port: 6379
    password: redis-prod-pass
  datasource:
    url: jdbc:mysql://prod-db:3306/mall?useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: root
    hikari:
      minimumIdle: 5
      maximumPoolSize: 10
      dataSourceProperties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true

mybatis-plus.global-config.banner: false
