
server.port: 8686

online: false
log:
  level: debug
  sqlLevel: debug
  thirdLevel: warn
  # filePath: /path/  # 日志存放目录, 默认是 ~/logs
  # maxHistory: 7     # 日志保留天数, 默认是 15

spring:
  profiles.active: dev
  application.name: web-backend
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false
#  session:
#    store-type: redis
  redis:
    host: dev-redis
    port: 6379
  jackson:
    # 将驼峰(userName)转成下划线(user_name)返回
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&queryInterceptors=com.github.common.sql.ShowSqlInterceptor
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    hikari:
      minimumIdle: 1
      maximumPoolSize: 1

# 连接池数量见: https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing

mybatis-plus:
  global-config.banner: false
  type-enums-package: com.*.*.enums
