
server.port: 8686

online: false

log:
  level: debug
  sqlLevel: debug
  thirdLevel: warn
  maxHistory: 7       # 日志保留天数, 默认是 30
  # filePath: /path/  # 日志存放目录, 默认是 ~/logs

spring:
  application.name: web-backend
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false
  messages.basename: i18n/message
  data.redis:
    host: test-redis
    port: 6379
    password: redis-test-pass
  datasource:
    url: jdbc:mysql://test-db:3306/mall?useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&queryInterceptors=com.github.common.sql.ShowSqlInterceptor
    username: root
    password: root
    hikari:
      minimumIdle: 2
      maximumPoolSize: 2
      dataSourceProperties:
        prepStmtCacheSize: 50
        prepStmtCacheSqlLimit: 128
        cachePrepStmts: true
        useServerPrepStmts: false

