
server.port: 8686
logging.config: classpath:log-test.xml

online: false

spring:
  application.name: web-backend
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false
#  session:
#    store-type: redis
  redis:
    host: test-redis
    port: 6379
    password: redis-test-pass
  datasource:
    url: jdbc:mysql://test-db:3306/mall?useAffectedRows=true&useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&queryInterceptors=com.github.common.sql.ShowSql8Interceptor
    username: root
    password: root
    hikari:
      minimumIdle: 2
      maximumPoolSize: 2
      dataSourceProperties:
        prepStmtCacheSize: 50
        prepStmtCacheSqlLimit: 128
        cachePrepStmts: true
        useServerPrepStmts: false

