
server.port: 8686

online: false
log:
  level: debug
  sqlLevel: debug
  thirdLevel: warn

spring:
  profiles.active: dev
  application.name: web-backend
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false
#  session:
#    store-type: redis
  redis:
    host: dev-redis
    port: 6379
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&statementInterceptors=com.github.common.sql.ShowSql5Interceptor
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    hikari:
      minimumIdle: 1
      maximumPoolSize: 1

# 连接池数量见: https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing

mybatis-plus:
  global-config.banner: false
  type-enums-package: com.*.*.enums
