
server.port: 8686

online: false

spring:
  profiles.active: dev
  application.name: web-backend
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false
#  session:
#    store-type: redis
  redis:
    host: dev-redis
    port: 6379
  datasource:
    url: jdbc:mysql://dev-db:3306/mall?useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&queryInterceptors=com.github.common.sql.ShowSql8Interceptor
    username: root
    password: root
    hikari:
      minimumIdle: 1
      maximumPoolSize: 1

# 连接池数量见: https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing

mybatis-plus:
  global-config.banner: false
